// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DGC.eKYC.Dal.Models;
using Microsoft.EntityFrameworkCore;

namespace DGC.eKYC.Dal.Contexts;

public partial class EKycContext : DbContext
{
    public EKycContext(DbContextOptions<EKycContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<AutoCapture> AutoCaptures { get; set; }

    public virtual DbSet<BillTransaction> BillTransactions { get; set; }

    public virtual DbSet<BillTransactionDetail> BillTransactionDetails { get; set; }

    public virtual DbSet<DeepLinkRequest> DeepLinkRequests { get; set; }

    public virtual DbSet<DocumentType> DocumentTypes { get; set; }

    public virtual DbSet<EkycTransaction> EkycTransactions { get; set; }

    public virtual DbSet<EkycTransactionDetail> EkycTransactionDetails { get; set; }

    public virtual DbSet<EkycTransactionType> EkycTransactionTypes { get; set; }

    public virtual DbSet<FacialVerification> FacialVerifications { get; set; }

    public virtual DbSet<Liveliness> Livelinesses { get; set; }

    public virtual DbSet<OcrNid> OcrNids { get; set; }

    public virtual DbSet<OcrPassport> OcrPassports { get; set; }

    public virtual DbSet<OrgChannel> OrgChannels { get; set; }

    public virtual DbSet<OrgDgconnectClient> OrgDgconnectClients { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PoTcheckExistingNid> PoTcheckExistingNids { get; set; }

    public virtual DbSet<PoTcompareFaceExistingNid> PoTcompareFaceExistingNids { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleHasPermission> RoleHasPermissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserHasPermission> UserHasPermissions { get; set; }

    public virtual DbSet<UserHasRole> UserHasRoles { get; set; }

    public virtual DbSet<UserLog> UserLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.ToTable("AuditLog");

            entity.HasIndex(e => new { e.DeepLinkRequestId, e.Timestamp }, "IX_AuditLog_DeepLinkRequestId_Timestamp");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AuditLog_Timestamp");

            entity.HasOne(d => d.DeepLinkRequest).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.DeepLinkRequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuditLog_DeepLinkRequest");
        });

        modelBuilder.Entity<AutoCapture>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId }).HasName("PK_AutoCaptures");

            entity.ToTable("AutoCapture");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AutoCaptures_CreatedAt");

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.AutoCapture)
                .HasForeignKey<AutoCapture>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoCaptures_EkycTransactionDetail");
        });

        modelBuilder.Entity<BillTransaction>(entity =>
        {
            entity.ToTable("BillTransaction");

            entity.HasIndex(e => new { e.IssuedDate, e.OrgId }, "IX_BillTransaction_IssuedDate_OrgId");

            entity.HasIndex(e => new { e.OrgId, e.IssuedDate }, "IX_BillTransaction_OrgId_IssuedDate");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BillTransaction_CreatedAt");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.ReferenceNo).HasMaxLength(125);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionNo).HasMaxLength(150);

            entity.HasOne(d => d.Org).WithMany(p => p.BillTransactions)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillTransaction_Organization");
        });

        modelBuilder.Entity<BillTransactionDetail>(entity =>
        {
            entity.ToTable("BillTransactionDetail");

            entity.HasIndex(e => e.BillingTransactionId, "IX_BillTransactionDetail_BillingTransactionId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BillTransactionDetail_CreatedAt");
            entity.Property(e => e.TotalAutoCaptureAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalFacialVerificationAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalFullProcessAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalLivelinessAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalOcrAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.BillingTransaction).WithMany(p => p.BillTransactionDetails)
                .HasForeignKey(d => d.BillingTransactionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillTransactionDetail_BillTransaction");
        });

        modelBuilder.Entity<DeepLinkRequest>(entity =>
        {
            entity.ToTable("DeepLinkRequest");

            entity.HasIndex(e => new { e.CreatedAt, e.OrgId }, "IX_DeepLinkRequest_CreatedAt_OrgId");

            entity.HasIndex(e => new { e.DealerId, e.IsUsed, e.CreatedAt }, "IX_DeepLinkRequest_DealerId_IsUsed_RequestedAt");

            entity.HasIndex(e => e.PhoneNumber, "IX_DeepLinkRequest_PhoneNumber").HasFilter("([PhoneNumber] IS NOT NULL)");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CallBackUrl)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.ChannelName)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.ClientIpAddress).HasMaxLength(64);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_DeepLinkRequest_RequestedAt");
            entity.Property(e => e.DealerId)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.DealerName).HasMaxLength(128);
            entity.Property(e => e.IsUsed).HasAnnotation("Relational:DefaultConstraintName", "DF_DeepLinkRequest_IsUsed");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UserAgent).HasMaxLength(512);

            entity.HasOne(d => d.Org).WithMany(p => p.DeepLinkRequests)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeepLinkRequest_Organization");

            entity.HasOne(d => d.OrgChannel).WithMany(p => p.DeepLinkRequests)
                .HasForeignKey(d => new { d.ChannelName, d.OrgId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeepLinkRequest_OrgChannel");
        });

        modelBuilder.Entity<DocumentType>(entity =>
        {
            entity.ToTable("DocumentType");

            entity.HasIndex(e => new { e.Id, e.DisabledDate }, "IX_DocumentType_DisabledDate_Id");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_DocumentType_CreatedDate");
            entity.Property(e => e.NameEn)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.NameKh)
                .IsRequired()
                .HasMaxLength(64);
        });

        modelBuilder.Entity<EkycTransaction>(entity =>
        {
            entity.ToTable("EkycTransaction");

            entity.HasIndex(e => new { e.CreatedAt, e.OrgId }, "IX_EkycTransaction_CreatedAt_OrgId");

            entity.HasIndex(e => e.DeeplinkRequestId, "IX_EkycTransaction_DeeplinkRequestId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EkycTransaction_CreatedAt");
            entity.Property(e => e.DealerId).HasMaxLength(64);
            entity.Property(e => e.DeviceOsVersion).HasMaxLength(255);
            entity.Property(e => e.EkycOption).HasMaxLength(20);
            entity.Property(e => e.OsType).HasMaxLength(255);
            entity.Property(e => e.SuperAppDeviceId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SuperAppUserId)
                .IsRequired()
                .HasMaxLength(36);

            entity.HasOne(d => d.DeeplinkRequest).WithOne(p => p.EkycTransaction)
                .HasForeignKey<EkycTransaction>(d => d.DeeplinkRequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EkycTransaction_DeepLinkRequest");

            entity.HasOne(d => d.DocumentType).WithMany(p => p.EkycTransactions)
                .HasForeignKey(d => d.DocumentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EkycTransaction_DocumentType");

            entity.HasOne(d => d.Org).WithMany(p => p.EkycTransactions)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EkycTransaction_Organization");
        });

        modelBuilder.Entity<EkycTransactionDetail>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.Id });

            entity.ToTable("EkycTransactionDetail");

            entity.HasIndex(e => new { e.EkycTransactionId, e.EkycTransactionTypeId }, "IX_EkycTransactionDetail_EkycTransactionId_Id");

            entity.HasOne(d => d.EkycTransaction).WithMany(p => p.EkycTransactionDetails)
                .HasForeignKey(d => d.EkycTransactionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EkycTransactionDetail_EkycTransaction");

            entity.HasOne(d => d.EkycTransactionType).WithMany(p => p.EkycTransactionDetails)
                .HasForeignKey(d => d.EkycTransactionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EkycTransactionDetail_EkycTransactionType");
        });

        modelBuilder.Entity<EkycTransactionType>(entity =>
        {
            entity.ToTable("EkycTransactionType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EkycTransactionType_CreatedAt");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EkycTransactionType_IsActive");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UnitTypeName)
                .IsRequired()
                .HasMaxLength(125);
        });

        modelBuilder.Entity<FacialVerification>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId });

            entity.ToTable("FacialVerification");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_FacialVerification_CreatedAt");

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.FacialVerification)
                .HasForeignKey<FacialVerification>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacialVerification_EkycTransactionDetail");
        });

        modelBuilder.Entity<Liveliness>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId });

            entity.ToTable("Liveliness");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Liveliness_CreatedAt");

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.Liveliness)
                .HasForeignKey<Liveliness>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Liveliness_EkycTransactionDetail");
        });

        modelBuilder.Entity<OcrNid>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId });

            entity.ToTable("OcrNid");

            entity.HasIndex(e => e.IdNumber, "IX_OcrNid_IdNumber");

            entity.Property(e => e.BirthDate).HasMaxLength(255);
            entity.Property(e => e.BirthPlace).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OcrNid_CreatedAt");
            entity.Property(e => e.ExpiryDate).HasMaxLength(255);
            entity.Property(e => e.Height).HasMaxLength(50);
            entity.Property(e => e.IdNumber).HasMaxLength(125);
            entity.Property(e => e.IssueDate).HasMaxLength(255);
            entity.Property(e => e.MinistryCode).HasMaxLength(500);
            entity.Property(e => e.NameEn).HasMaxLength(255);
            entity.Property(e => e.NameKh).HasMaxLength(255);
            entity.Property(e => e.ProfileType)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Sex).HasMaxLength(25);

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.OcrNid)
                .HasForeignKey<OcrNid>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OcrNid_EkycTransactionDetail");
        });

        modelBuilder.Entity<OcrPassport>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId });

            entity.ToTable("OcrPassport");

            entity.HasIndex(e => e.PassportNumber, "IX_OcrPassport_PassportNumber");

            entity.Property(e => e.Confidence).HasMaxLength(255);
            entity.Property(e => e.CountryCode).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OcrPassport_CreatedAt");
            entity.Property(e => e.DateOfBirth).HasMaxLength(255);
            entity.Property(e => e.DateOfExpiry).HasMaxLength(255);
            entity.Property(e => e.GivenName).HasMaxLength(255);
            entity.Property(e => e.PassportNumber).HasMaxLength(255);
            entity.Property(e => e.Sex).HasMaxLength(255);
            entity.Property(e => e.Surname).HasMaxLength(255);

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.OcrPassport)
                .HasForeignKey<OcrPassport>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OcrPassport_EkycTransactionDetail");
        });

        modelBuilder.Entity<OrgChannel>(entity =>
        {
            entity.HasKey(e => new { e.ChannelName, e.OrgId });

            entity.ToTable("OrgChannel");

            entity.HasIndex(e => e.OrgId, "IX_OrgChannel_OrgId");

            entity.Property(e => e.ChannelName).HasMaxLength(64);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrgChannel_CreatedDate");

            entity.HasOne(d => d.Org).WithMany(p => p.OrgChannels)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrgChannel_Organization");
        });

        modelBuilder.Entity<OrgDgconnectClient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Client");

            entity.ToTable("OrgDGConnectClient");

            entity.Property(e => e.Id).HasMaxLength(64);
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Client_CreatedAt");

            entity.HasOne(d => d.Org).WithMany(p => p.OrgDgconnectClients)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Client_Organization");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.ToTable("Organization");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CountryContactCode).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Organization_CreatedAt");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Organization_IsActive");
            entity.Property(e => e.OrgName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.OrgType).HasMaxLength(255);
            entity.Property(e => e.PhoneNo).HasMaxLength(255);
            entity.Property(e => e.VatNo).HasMaxLength(255);
            entity.Property(e => e.WebsiteUrl).HasMaxLength(255);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.ToTable("Permission");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permission_CreatedAt");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<PoTcheckExistingNid>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId }).HasName("PK_PoTProfileMatching");

            entity.ToTable("PoTCheckExistingNid");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PoTProfileMatching_CreatedAt");
            entity.Property(e => e.SessionToken).HasMaxLength(64);

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.PoTcheckExistingNid)
                .HasForeignKey<PoTcheckExistingNid>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PoTProfileMatching_EkycTransactionDetail");
        });

        modelBuilder.Entity<PoTcompareFaceExistingNid>(entity =>
        {
            entity.HasKey(e => new { e.EkycTransactionId, e.EkycTransactionDetailId });

            entity.ToTable("PoTCompareFaceExistingNid");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PoTCompareFaceExistingNid_CreatedAt");
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.NameEn).HasMaxLength(128);
            entity.Property(e => e.NameKh).HasMaxLength(128);
            entity.Property(e => e.NidImageUrl).HasMaxLength(128);
            entity.Property(e => e.NidNumber).HasMaxLength(20);

            entity.HasOne(d => d.EkycTransactionDetail).WithOne(p => p.PoTcompareFaceExistingNid)
                .HasForeignKey<PoTcompareFaceExistingNid>(d => new { d.EkycTransactionId, d.EkycTransactionDetailId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PoTCompareFaceExistingNid_EkycTransactionDetail");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Role_CreatedAt");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(125);
        });

        modelBuilder.Entity<RoleHasPermission>(entity =>
        {
            entity.ToTable("RoleHasPermission");

            entity.HasIndex(e => new { e.RoleId, e.PermissionId }, "UQ_RoleHasPermission_RolePerm").IsUnique();

            entity.HasOne(d => d.Permission).WithMany(p => p.RoleHasPermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleHasPermission_Permission");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleHasPermissions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleHasPermission_Role");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.HasIndex(e => e.OrgId, "IX_User_OrgId");

            entity.Property(e => e.AliaEmail).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_User_CreatedAt");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.IdSub).HasMaxLength(255);
            entity.Property(e => e.IdpProvider).HasMaxLength(255);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_User_IsActive");
            entity.Property(e => e.MobileNo).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RememberToken).HasMaxLength(255);

            entity.HasOne(d => d.Org).WithMany(p => p.Users)
                .HasForeignKey(d => d.OrgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Organization");
        });

        modelBuilder.Entity<UserHasPermission>(entity =>
        {
            entity.ToTable("UserHasPermission");

            entity.HasIndex(e => new { e.PermissionId, e.UserId }, "UQ_UserHasPermission_UserPerm").IsUnique();

            entity.HasOne(d => d.Permission).WithMany(p => p.UserHasPermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserHasPermission_Permission");

            entity.HasOne(d => d.User).WithMany(p => p.UserHasPermissions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserHasPermission_User");
        });

        modelBuilder.Entity<UserHasRole>(entity =>
        {
            entity.ToTable("UserHasRole");

            entity.HasOne(d => d.Role).WithMany(p => p.UserHasRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserHasRole_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserHasRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserHasRole_User");
        });

        modelBuilder.Entity<UserLog>(entity =>
        {
            entity.ToTable("UserLog");

            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "IX_UserLog_UserId_CreatedAt");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_CreatedAt");
            entity.Property(e => e.IpAddress).HasMaxLength(255);
            entity.Property(e => e.LogsType).HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.UserLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserLog_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}