// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class AuditLog
{
    public Guid Id { get; set; }

    public Guid DeepLinkRequestId { get; set; }

    public string Action { get; set; }

    public string Reason { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual DeepLinkRequest DeepLinkRequest { get; set; }
}