// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class AutoCapture
{
    public Guid EkycTransactionId { get; set; }

    public Guid EkycTransactionDetailId { get; set; }

    public string CaptureImg { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EkycTransactionDetail EkycTransactionDetail { get; set; }
}