// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class BillTransaction
{
    public Guid Id { get; set; }

    public int OrgId { get; set; }

    public string TransactionNo { get; set; }

    public string ReferenceNo { get; set; }

    public string Status { get; set; }

    public DateOnly? IssuedDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<BillTransactionDetail> BillTransactionDetails { get; set; } = new List<BillTransactionDetail>();

    public virtual Organization Org { get; set; }
}