// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class BillTransactionDetail
{
    public Guid Id { get; set; }

    public Guid BillingTransactionId { get; set; }

    public int? TotalAutoCapture { get; set; }

    public decimal? TotalAutoCaptureAmount { get; set; }

    public int? TotalOcr { get; set; }

    public decimal? TotalOcrAmount { get; set; }

    public int? TotalLiveliness { get; set; }

    public decimal? TotalLivelinessAmount { get; set; }

    public int? TotalFacialVerification { get; set; }

    public decimal? TotalFacialVerificationAmount { get; set; }

    public int? TotalFullProcess { get; set; }

    public decimal? TotalFullProcessAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual BillTransaction BillingTransaction { get; set; }
}