// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class DeepLinkRequest
{
    public Guid Id { get; set; }

    public int OrgId { get; set; }

    public string DealerId { get; set; }

    public string DealerName { get; set; }

    public string PhoneNumber { get; set; }

    public string CallBackUrl { get; set; }

    public string ChannelName { get; set; }

    public bool IsUsed { get; set; }

    public DateTime? UsedAt { get; set; }

    public string ClientIpAddress { get; set; }

    public string UserAgent { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual EkycTransaction EkycTransaction { get; set; }

    public virtual Organization Org { get; set; }

    public virtual OrgChannel OrgChannel { get; set; }
}