// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class DocumentType
{
    public int Id { get; set; }

    public string NameEn { get; set; }

    public string NameKh { get; set; }

    public DateTime? DisabledDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<EkycTransaction> EkycTransactions { get; set; } = new List<EkycTransaction>();
}