// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class EkycTransaction
{
    public Guid Id { get; set; }

    public int OrgId { get; set; }

    public string DealerId { get; set; }

    public string OsType { get; set; }

    public string SuperAppUserId { get; set; }

    public string SuperAppDeviceId { get; set; }

    public string DeviceOsVersion { get; set; }

    public string EkycOption { get; set; }

    public int DocumentTypeId { get; set; }

    public Guid DeeplinkRequestId { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? RetrievedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual DeepLinkRequest DeeplinkRequest { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual ICollection<EkycTransactionDetail> EkycTransactionDetails { get; set; } = new List<EkycTransactionDetail>();

    public virtual Organization Org { get; set; }
}