// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class EkycTransactionDetail
{
    public Guid Id { get; set; }

    public Guid EkycTransactionId { get; set; }

    public int EkycTransactionTypeId { get; set; }

    public bool IsSucceed { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AutoCapture AutoCapture { get; set; }

    public virtual EkycTransaction EkycTransaction { get; set; }

    public virtual EkycTransactionType EkycTransactionType { get; set; }

    public virtual FacialVerification FacialVerification { get; set; }

    public virtual Liveliness Liveliness { get; set; }

    public virtual OcrNid OcrNid { get; set; }

    public virtual OcrPassport OcrPassport { get; set; }

    public virtual PoTcheckExistingNid PoTcheckExistingNid { get; set; }

    public virtual PoTcompareFaceExistingNid PoTcompareFaceExistingNid { get; set; }
}