// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class EkycTransactionType
{
    public int Id { get; set; }

    public string UnitTypeName { get; set; }

    public decimal? UnitPrice { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<EkycTransactionDetail> EkycTransactionDetails { get; set; } = new List<EkycTransactionDetail>();
}