// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class OcrNid
{
    public Guid EkycTransactionId { get; set; }

    public Guid EkycTransactionDetailId { get; set; }

    public string IdNumber { get; set; }

    public string ProfileType { get; set; }

    public string NameKh { get; set; }

    public string NameEn { get; set; }

    public string BirthDate { get; set; }

    public string Sex { get; set; }

    public string Height { get; set; }

    public string BirthPlace { get; set; }

    public string Address { get; set; }

    public string IssueDate { get; set; }

    public string ExpiryDate { get; set; }

    public string Description { get; set; }

    public string MinistryCode { get; set; }

    public string PortraitImg { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EkycTransactionDetail EkycTransactionDetail { get; set; }
}