// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class OcrPassport
{
    public Guid EkycTransactionId { get; set; }

    public Guid EkycTransactionDetailId { get; set; }

    public string CountryCode { get; set; }

    public string PassportNumber { get; set; }

    public string Surname { get; set; }

    public string GivenName { get; set; }

    public string Sex { get; set; }

    public string DateOfBirth { get; set; }

    public string DateOfExpiry { get; set; }

    public string PortraitImg { get; set; }

    public string Confidence { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EkycTransactionDetail EkycTransactionDetail { get; set; }
}