// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class Organization
{
    public int Id { get; set; }

    public string OrgName { get; set; }

    public bool IsActive { get; set; }

    public string Address { get; set; }

    public string PhoneNo { get; set; }

    public string VatNo { get; set; }

    public string WebsiteUrl { get; set; }

    public string CountryContactCode { get; set; }

    public int? City { get; set; }

    public string OrgType { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<BillTransaction> BillTransactions { get; set; } = new List<BillTransaction>();

    public virtual ICollection<DeepLinkRequest> DeepLinkRequests { get; set; } = new List<DeepLinkRequest>();

    public virtual ICollection<EkycTransaction> EkycTransactions { get; set; } = new List<EkycTransaction>();

    public virtual ICollection<OrgChannel> OrgChannels { get; set; } = new List<OrgChannel>();

    public virtual ICollection<OrgDgconnectClient> OrgDgconnectClients { get; set; } = new List<OrgDgconnectClient>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}