// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class OrgChannel
{
    public string ChannelName { get; set; }

    public int OrgId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<DeepLinkRequest> DeepLinkRequests { get; set; } = new List<DeepLinkRequest>();

    public virtual Organization Org { get; set; }
}