// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class PoTcompareFaceExistingNid
{
    public Guid EkycTransactionId { get; set; }

    public Guid EkycTransactionDetailId { get; set; }

    public bool IsVerified { get; set; }

    public Guid TrackingId { get; set; }

    public string NidNumber { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string NameKh { get; set; }

    public string NameEn { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public string NidImageUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual EkycTransactionDetail EkycTransactionDetail { get; set; }
}