// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class User
{
    public int Id { get; set; }

    public int OrgId { get; set; }

    public string IdSub { get; set; }

    public string Name { get; set; }

    public string RememberToken { get; set; }

    public string Email { get; set; }

    public string AliaEmail { get; set; }

    public DateTime? EmailVerifiedAt { get; set; }

    public string MobileNo { get; set; }

    public bool FirstLogin { get; set; }

    public DateTime? LastLogin { get; set; }

    public string IdpProvider { get; set; }

    public bool IsForceLogout { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Organization Org { get; set; }

    public virtual ICollection<UserHasPermission> UserHasPermissions { get; set; } = new List<UserHasPermission>();

    public virtual ICollection<UserHasRole> UserHasRoles { get; set; } = new List<UserHasRole>();

    public virtual ICollection<UserLog> UserLogs { get; set; } = new List<UserLog>();
}