// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class UserHasPermission
{
    public int Id { get; set; }

    public int PermissionId { get; set; }

    public int UserId { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual User User { get; set; }
}