// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class UserLog
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string LogsType { get; set; }

    public string LogsDescription { get; set; }

    public string IpAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}