using Asp.Versioning;
using DGC.eKYC.Business.DTOs.Deeplink;
using DGC.eKYC.Business.DTOs.Errors;
using DGC.eKYC.Business.Mapper;
using DGC.eKYC.Business.Services.Deeplink;
using DGC.eKYC.Business.Validations.Api;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace DGC.eKYC.Api.Controllers.v2025_11_20;

[ApiController]
[Route("api/deeplink")]
[ApiVersion("2025-11-20")]
[Produces("application/json")]
public class DeeplinkController(
    ILogger<DeeplinkController> logger,
    IDeeplinkService deeplinkService) : ControllerBase
{
    private readonly ILogger<DeeplinkController> _logger = logger;
    private readonly IDeeplinkService _deeplinkService = deeplinkService;

    /// <summary>
    /// Validate Deeplink Generated by Function to MNO Server
    /// </summary>
    /// <param name="validateDeeplinkInputDto">Validate Deeplink Input DTO</param>
    /// <param name="cancellationToken">cancellation token.</param>
    /// <returns>HTTP 200 OK with no response body.</returns>
    [SuperAppHashValidation]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ValidateDeeplinkOutputDto))]
    [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ErrorResponse))]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests, Type = typeof(ErrorResponse))]
    [ProducesResponseType(StatusCodes.Status500InternalServerError, Type = typeof(ErrorResponse))]
    [HttpPost("validate-mno")]
    public async Task<IActionResult> PostValidateDeeplink([FromBody] ValidateDeeplinkInputDto validateDeeplinkInputDto, CancellationToken cancellationToken)
    {
        // Get raw User-Agent
        var userAgent = Request.Headers["User-Agent"].ToString();

        // Respect X-Forwarded-For when behind a proxy/load balancer
        var xForwardedFor = Request.Headers["X-Forwarded-For"].FirstOrDefault();
        var clientIp = !string.IsNullOrEmpty(xForwardedFor)
            ? xForwardedFor.Split(',').Select(s => s.Trim()).FirstOrDefault()
            : HttpContext.Connection.RemoteIpAddress?.ToString();

        // Parse OS and OS version from User-Agent (best-effort)
        (validateDeeplinkInputDto.Os, validateDeeplinkInputDto.OsVersion) = ParseOsFromUserAgent(userAgent);

        validateDeeplinkInputDto.ToCleaned();
        validateDeeplinkInputDto.IpAddress = clientIp;
        validateDeeplinkInputDto.UserAgent = userAgent;

        var tokenResponse = await _deeplinkService.ValidateDeeplink(validateDeeplinkInputDto, cancellationToken);
        return Ok(tokenResponse);
    }

    private static (string os, string osVersion) ParseOsFromUserAgent(string ua)
    {
        if (string.IsNullOrEmpty(ua)) return ("Unknown", "Unknown");

        // Windows
        var m = Regex.Match(ua, "Windows NT ([0-9\\.]+)");
        if (m.Success) return ("Windows", m.Groups[1].Value);

        // Android
        m = Regex.Match(ua, "Android ([0-9\\.]+)");
        if (m.Success) return ("Android", m.Groups[1].Value);

        // iOS (iPhone/iPad)
        m = Regex.Match(ua, "(?:iPhone OS|CPU OS) ([0-9_]+)");
        if (m.Success) return ("iOS", m.Groups[1].Value.Replace('_', '.'));

        // macOS
        m = Regex.Match(ua, "Mac OS X ([0-9_]+)");
        if (m.Success) return ("macOS", m.Groups[1].Value.Replace('_', '.'));

        return ("Unknown", "Unknown");
    }
}