using Asp.Versioning;
using DGC.eKYC.Business.DTOs.Errors;
using DGC.eKYC.Business.DTOs.SuperAppSecurity;
using DGC.eKYC.Business.Services.Deeplink;
using DGC.eKYC.Business.Validations.Api;
using Microsoft.AspNetCore.Mvc;

namespace DGC.eKYC.Api.Controllers.v2025_11_20;

[ApiController]
[Route("api/ekyc")]
[ApiVersion("2025-11-20")]
[Produces("application/json")]
public class EKycController(
    ILogger<EKycController> logger,
    IDeeplinkService deeplinkService) : ControllerBase
{
    private readonly ILogger<EKycController> _logger = logger;
    private readonly IDeeplinkService _deeplinkService = deeplinkService;

    /// <summary>
    /// Validate Deeplink Generated by Function to MNO Server
    /// </summary>
    /// <param name="data">Validate Deeplink Input DTO</param>
    /// <param name="cancellationToken">cancellation token.</param>
    /// <returns>HTTP 200 OK with no response body.</returns>
    [SuperAppHashValidation]
    [JwtInternalAuthorizationValidation]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ErrorResponse))]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests, Type = typeof(ErrorResponse))]
    [ProducesResponseType(StatusCodes.Status500InternalServerError, Type = typeof(ErrorResponse))]
    [HttpPost("test")]
    public async Task<IActionResult> PostValidateTest([FromBody] TestC data, CancellationToken cancellationToken)
    {
        return Ok();
    }
}

public class TestC : SuperAppSecurityBaseInput
{
}